language: python
sudo: false

python:
  "3.6"

env:
  - LUA="lua 5.3"       COMPAT=default
  - LUA="lua 5.3"       COMPAT=none
  - LUA="lua 5.3"       COMPAT=default  CFLAGS="-DLUA_NOCVTN2S -DLUA_NOCVTS2N"

before_install:
  - pip install hererocks
  - hererocks HERE --$LUA --compat $COMPAT --cflags="$CFLAGS" --no-readline --luarocks latest --verbose
  - hererocks HERE --show
  - source HERE/bin/activate

install:
  - luarocks install luacheck
  - luarocks install luacov-coveralls

script:
  - python build.py
  - lua module.lua