db.objects.Rowlet={
    id=722,
    species="Grass.Quill.Pokémon",
    types={14,13},
    region="alola",
    gender=2,
    height=0.3,
    weight=1.5,
    images={
        normal={"166441fa0ec","166441f81a8"},
        shiny={"166441fd560","166441fbd14"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Dartrix={
    id=723,
    species="Blade.Quill.Pokémon",
    types={14,13},
    region="alola",
    gender=2,
    height=0.7,
    weight=16.0,
    images={
        normal={"16644225f2f","166442246e9"},
        shiny={"16644222ae9","166442211af"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Decidueye={
    id=724,
    species="Arrow.Quill.Pokémon",
    types={14,5},
    region="alola",
    gender=2,
    height=1.6,
    weight=36.6,
    images={
        normal={"166442528b7","166442528b7"},
        shiny={"16644250974","1664424e940"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Litten={
    id=725,
    species="Fire.Cat.Pokémon",
    types={4},
    region="alola",
    gender=2,
    height=0.4,
    weight=4.3,
    images={
        normal={"166444377a5","16644435f7f"},
        shiny={"1664443403c","166444327b5"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Torracat={
    id=726,
    species="Fire.Cat.Pokémon",
    types={4},
    region="alola",
    gender=2,
    height=0.7,
    weight=25.0,
    images={
        normal={"16644551dde","166445504c5"},
        shiny={"1664454e8c5","1664454d057"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Incineroar={
    id=727,
    species="Heel.Pokémon",
    types={4,10},
    region="alola",
    gender=2,
    height=1.8,
    weight=83.0,
    images={
        normal={"1665b090bc3","1665b092336"},
        shiny={"1665b09569f","1665b093f2c"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Popplio={
    id=728,
    species="Sea.Lion.Pokémon",
    types={18},
    region="alola",
    gender=2,
    height=0.4,
    weight=7.5,
    images={
        normal={"1667417c843", "1667417dfb5"},
        shiny={"16674188175","16674186a03"},
        left={0,2},
        right={nil,nil}
    }
}

db.objects.Brionne={
    id=729,
    species="Pop.Star.Pokémon",
    types={18},
    region="alola",
    gender=2,
    height=0.6,
    weight=17.5,
    images={
        normal={"166741c9045","166741c9045"},
        shiny={"166741cf64e","166741cbf2f"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Primarina={
    id=730,
    species="Soloist.Pokémon",
    types={18,3},
    region="alola",
    gender=2,
    height=1.8,
    weight=44.0,
    images={
        normal={"16674209584","1667420d2ae"},
        shiny={"166741f42b4","166742047c3"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Pikipek={
    id=731,
    species="Woodpecker.Pokémon",
    types={7,13},
    region="alola",
    gender=2,
    height=0.3,
    weight=1.2,
    images={
        normal={"166742f669e","166742f9237"},
        shiny={"166742e396b","166742f524e"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Trumbeak={
    id=732,
    species="Bugle.Beak.Pokémon",
    types={7,13},
    region="alola",
    gender=2,
    height=0.6,
    weight=14.8,
    images={
        normal={"16674378203","1667437b515"},
        shiny={"1667438af9c","1667439aa20"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Toucannon={
    id=733,
    species="Cannon.Pokémon",
    types={7,13},
    region="alola",
    gender=2,
    height=1.1,
    weight=26.0,
    images={
        normal={"166743b6c68","166743b9905"},
        shiny={"166743b3d84","166743b54f5"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Yungoos={
    id=734,
    species="Loitering.Pokémon",
    types={7},
    region="alola",
    gender=2,
    height=0.4,
    weight=6.0,
    images={
        normal={"166743f5079","166743f67ea"},
        shiny={"166743e3d0c","166743f378b"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Gumshoos={
    id=735,
    species="Stakeout.Pokémon",
    types={7},
    region="alola",
    gender=2,
    height=0.7,
    weight=14.2,
    images={
        normal={"1667449a0a1","1667448a62e"},
        shiny={"16674485992","16674484220"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Grubbin={
    id=736,
    species="Larva.Pokémon",
    types={1},
    region="alola",
    gender=2,
    height=0.4,
    weight=4.4,
    images={
        normal={"166744b9d7b","166744b860a"},
        shiny={"166744b6e97","166744b5726"},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Charjabug={
    id=737,
    species="Battery.Pokémon",
    types={1,11},
    region="alola",
    gender=2,
    height=0.5,
    weight=10.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Vikavolt={
    id=738,
    species="Stag.Beetle.Pokémon",
    types={1,11},
    region="alola",
    gender=2,
    height=1.5,
    weight=45.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Crabrawler={
    id=739,
    species="Boxing.Pokémon",
    types={12},
    region="alola",
    gender=2,
    height=0.6,
    weight=7.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Crabominable={
    id=740,
    species="Woolly.Crab.Pokémon",
    types={12,15},
    region="alola",
    gender=2,
    height=1.7,
    weight=180.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Oricorio={
    id=741,
    species="Dancing.Pokémon",
    types={4,13},
    region="alola",
    gender=2,
    height=0.6,
    weight=3.4,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Cutiefly={
    id=742,
    species="Bee.Fly.Pokémon",
    types={1,3},
    region="alola",
    gender=2,
    height=0.1,
    weight=0.2,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Ribombee={
    id=743,
    species="Bee.Fly.Pokémon",
    types={1,3},
    region="alola",
    gender=2,
    height=0.2,
    weight=0.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Rockruff={
    id=744,
    species="Puppy.Pokémon",
    types={17},
    region="alola",
    gender=2,
    height=0.5,
    weight=9.2,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Lycanroc={
    id=745,
    species="Wolf.Pokémon",
    types={17},
    region="alola",
    gender=2,
    height=0.8,
    weight=25.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Wishiwashi={
    id=746,
    species="Small.Fry.Pokémon",
    types={18},
    region="alola",
    gender=2,
    height=0.2,
    weight=0.3,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Mareanie={
    id=747,
    species="Brutal.Star.Pokémon",
    types={16,18},
    region="alola",
    gender=2,
    height=0.4,
    weight=8.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Toxapex={
    id=748,
    species="Brutal.Star.Pokémon",
    types={16,18},
    region="alola",
    gender=2,
    height=0.7,
    weight=14.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Mudbray={
    id=749,
    species="Donkey.Pokémon",
    types={6},
    region="alola",
    gender=2,
    height=1.0,
    weight=110.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Mudsdale={
    id=750,
    species="Draft.Horse.Pokémon",
    types={6},
    region="alola",
    gender=2,
    height=2.5,
    weight=920.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Dewpider={
    id=751,
    species="Water.Bubble.Pokémon",
    types={18,1},
    region="alola",
    gender=2,
    height=0.3,
    weight=4.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Araquanid={
    id=752,
    species="Water.Bubble.Pokémon",
    types={18,1},
    region="alola",
    gender=2,
    height=1.8,
    weight=82.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Fomantis={
    id=753,
    species="Sickle.Grass.Pokémon",
    types={14},
    region="alola",
    gender=2,
    height=0.3,
    weight=1.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Lurantis={
    id=754,
    species="Bloom.Sickle.Pokémon",
    types={14},
    region="alola",
    gender=2,
    height=0.9,
    weight=18.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Morelull={
    id=755,
    species="Illuminating.Pokémon",
    types={14,3},
    region="alola",
    gender=2,
    height=0.2,
    weight=1.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Shiinotic={
    id=756,
    species="Illuminating.Pokémon",
    types={14,3},
    region="alola",
    gender=2,
    height=1.0,
    weight=11.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Salandit={
    id=757,
    species="Toxic.Lizard.Pokémon",
    types={16,4},
    region="alola",
    gender=2,
    height=0.6,
    weight=4.8,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Salazzle={
    id=758,
    species="Toxic.Lizard.Pokémon",
    types={16,4},
    region="alola",
    gender=1,
    height=1.2,
    weight=22.2,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Salazzle={
    id=758,
    species="Toxic.Lizard.Pokémon",
    types={16,4},
    region="alola",
    gender=1,
    height=1.2,
    weight=22.2,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Stufful={
    id=759,
    species="Flailing.Pokémon",
    types={7,12},
    region="alola",
    gender=2,
    height=0.5,
    weight=6.8,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Bewear={
    id=760,
    species="Strong.Arm.Pokémon",
    types={7,12},
    region="alola",
    gender=2,
    height=2.1,
    weight=135.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Bounsweet={
    id=761,
    species="Fruit.Pokémon",
    types={14},
    region="alola",
    gender=1,
    height=0.3,
    weight=3.2,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Steenee={
    id=762,
    species="Fruit.Pokémon",
    types={14},
    region="alola",
    gender=1,
    height=0.7,
    weight=8.2,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Tsareena={
    id=763,
    species="Fruit.Pokémon",
    types={14},
    region="alola",
    gender=1,
    height=1.2,
    weight=21.4,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Comfey={
    id=764,
    species="Posy.Picker.Pokémon",
    types={3},
    region="alola",
    gender=2,
    height=0.1,
    weight=0.3,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Oranguru={
    id=765,
    species="Sage.Pokémon",
    types={7,8},
    region="alola",
    gender=2,
    height=1.5,
    weight=76.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Passimian={
    id=766,
    species="Teamwork.Pokémon",
    types={12},
    region="alola",
    gender=2,
    height=2.0,
    weight=82.8,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Wimpod={
    id=767,
    species="Turn.Tail.Pokémon",
    types={1,18},
    region="alola",
    gender=2,
    height=0.5,
    weight=12.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Golisopod={
    id=768,
    species="Hard.Scale.Pokémon",
    types={1,18},
    region="alola",
    gender=2,
    height=2.0,
    weight=108.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Sandygast={
    id=769,
    species="Sand.Heap.Pokémon",
    types={5,6},
    region="alola",
    gender=2,
    height=0.5,
    weight=70.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Palossand={
    id=770,
    species="Sand.Castle.Pokémon",
    types={5,6},
    region="alola",
    gender=2,
    height=1.3,
    weight=250.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Pyukumuku={
    id=771,
    species="Sea.Cucumber.Pokémon",
    types={18},
    region="alola",
    gender=2,
    height=0.3,
    weight=1.2,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Typenull={
    id=772,
    species="Synthetic.Pokémon",
    types={7},
    region="alola",
    gender=2,
    height=1.9,
    weight=120.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Silvally={
    id=773,
    species="Synthetic.Pokémon",
    types={7},
    region="alola",
    gender=2,
    height=2.3,
    weight=100.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Minior={
    id=774,
    species="Meteor.Pokémon",
    types={17,13},
    region="alola",
    gender=2,
    height=0.3,
    weight=40.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Komala={
    id=775,
    species="Drowsing.Pokémon",
    types={7},
    region="alola",
    gender=2,
    height=0.4,
    weight=19.9,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Turtonator={
    id=776,
    species="Blast.Turtle.Pokémon",
    types={4,2},
    region="alola",
    gender=2,
    height=2.0,
    weight=212.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Togedemaru={
    id=777,
    species="Roly-Poly.Pokémon",
    types={11,9},
    region="alola",
    gender=2,
    height=0.3,
    weight=3.3,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Mimikyu={
    id=778,
    species="Disguise.Pokémon",
    types={5,3},
    region="alola",
    gender=2,
    height=0.2,
    weight=0.7,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Bruxish={
    id=779,
    species="Gnash.Teeth.Pokémon",
    types={18,8},
    region="alola",
    gender=2,
    height=0.9,
    weight=19.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Drampa={
    id=780,
    species="Placid.Pokémon",
    types={7,2},
    region="alola",
    gender=2,
    height=3.0,
    weight=185.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Dhelmise={
    id=781,
    species="Sea.Creeper.Pokémon",
    types={5,14},
    region="alola",
    gender=2,
    height=3.9,
    weight=210.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Jangmoo={
    id=782,
    species="Scaly.Pokémon",
    types={2},
    region="alola",
    gender=2,
    height=0.6,
    weight=29.7,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Hakamoo={
    id=783,
    species="Scaly.Pokémon",
    types={2,12},
    region="alola",
    gender=2,
    height=1.2,
    weight=47.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Kommoo={
    id=784,
    species="Scaly.Pokémon",
    types={2,12},
    region="alola",
    gender=2,
    height=1.6,
    weight=78.2,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Tapukoko={
    id=785,
    species="Land.Spirit.Pokémon",
    types={11,3},
    region="alola",
    gender=2,
    height=1.8,
    weight=20.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Tapulele={
    id=786,
    species="Land.Spirit.Pokémon",
    types={8,3},
    region="alola",
    gender=2,
    height=1.2,
    weight=18.6,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Tapubulu={
    id=787,
    species="Land.Spirit.Pokémon",
    types={14,3},
    region="alola",
    gender=2,
    height=1.9,
    weight=45.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Tapufini={
    id=788,
    species="Land.Spirit.Pokémon",
    types={18,3},
    region="alola",
    gender=2,
    height=1.3,
    weight=21.2,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Cosmog={
    id=789,
    species="Nebula.Pokémon",
    types={8},
    region="alola",
    gender=2,
    height=0.2,
    weight=0.1,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Cosmoem={
    id=790,
    species="Protostar.Pokémon",
    types={8},
    region="alola",
    gender=2,
    height=0.1,
    weight=999.9,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Solgaleo={
    id=791,
    species="Sunne.Pokémon",
    types={8,9},
    region="alola",
    gender=2,
    height=3.4,
    weight=230.0,
    images={
        normal={"15cf8c6749c", "15cf8c68f60"},
        shiny={"",""},
        left={0,-14},
        right={nil,nil}
    }
}

db.objects.Lunala={
    id=792,
    species="Moone.Pokémon",
    types={8,5},
    region="alola",
    gender=2,
    height=4.0,
    weight=120.0,
    images={
        normal={"15cf8c24cb9", "15cf8c2b0f5"},
        shiny={"",""},
        left={0,-29},
        right={nil,nil}
    }
}

db.objects.Nihilego={
    id=793,
    species="Parasite.Pokémon",
    types={17,16},
    region="alola",
    gender=2,
    height=1.2,
    weight=55.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Buzzwole={
    id=794,
    species="Swollen.Pokémon",
    types={1,12},
    region="alola",
    gender=2,
    height=2.4,
    weight=333.6,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Pheromosa={
    id=795,
    species="Lissome.Pokémon",
    types={1,12},
    region="alola",
    gender=2,
    height=1.8,
    weight=25.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Xurkitree={
    id=796,
    species="Glowing.Pokémon",
    types={11},
    region="alola",
    gender=2,
    height=3.8,
    weight=100.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Celesteela={
    id=797,
    species="Launch.Pokémon",
    types={9,13},
    region="alola",
    gender=2,
    height=9.2,
    weight=999.9,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Kartana={
    id=798,
    species="Drawn.Sword.Pokémon",
    types={14,9},
    region="alola",
    gender=2,
    height=0.3,
    weight=0.1,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Guzzlord={
    id=799,
    species="Junkivore.Pokémon",
    types={10,2},
    region="alola",
    gender=2,
    height=5.5,
    weight=888.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Necrozma={
    id=800,
    species="Prism.Pokémon",
    types={8},
    region="alola",
    gender=2,
    height=2.4,
    weight=230.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Magearna={
    id=801,
    species="Artificial.Pokémon",
    types={9,3},
    region="alola",
    gender=2,
    height=1.0,
    weight=80.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Marshadow={
    id=802,
    species="Gloomdweller.Pokémon",
    types={12,5},
    region="alola",
    gender=2,
    height=0.7,
    weight=22.2,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Poipole={
    id=803,
    species="Poison.Pin.Pokémon",
    types={16},
    region="alola",
    gender=2,
    height=0.6,
    weight=1.8,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Naganadel={
    id=804,
    species="Poison.Pin.Pokémon",
    types={16,2},
    region="alola",
    gender=2,
    height=3.6,
    weight=150.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Stakataka={
    id=805,
    species="Rampart.Pokémon",
    types={17,9},
    region="alola",
    gender=2,
    height=5.5,
    weight=820.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Blacephalon={
    id=806,
    species="Fireworks.Pokémon",
    types={4,5},
    region="alola",
    gender=2,
    height=1.8,
    weight=13.0,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

db.objects.Zeraora={
    id=807,
    species="Thunderclap.Pokémon",
    types={11},
    region="alola",
    gender=2,
    height=1.5,
    weight=44.5,
    images={
        normal={"",""},
        shiny={"",""},
        left={0,0},
        right={nil,nil}
    }
}

